### ISSUE TITLE
No anonymous Confluence usage possible

### ISSUE THREAD

**Issue by Kusig** [Fuchs/confluence-remote-user-sso#5]
We got the following important problem in relation to the "anonymous" usage right in Confluence. In order to reduce number of used licenses, often spaces are open for anonymous users which do only need read access.

If users are authenticated via Kerberos properly but they do not have a confluence license (they are not part of the "confluence-users" group), the access is not allowed anymore in Confluence.  As all inhouse users are usually properly kerberos authenticated, we have no way anymore to use the anonymous feature. We assume that the plugin does not treat this case properly actually.

Any hint or workaround how we could resolve this would be highly appreciated.

Regards
Markus

**Comment by Kusig** [comment]
From reading the code, I assume that the getUser(..) method does return always a user object because it found a valid kerberos header.  But for anonymous users it should return null I guess in this case.
This might probably return the user even if he isn't licensed (not assigned to confluence-user group)

`confluenceuser = super.getUser(username);`

As all users are available in the AD sync of Confluence it might find and return them even if not licensed (assumption so far).

**Comment by Fuchs** [comment]
Closed, read the readme, I'm afraid I can neither test nor work on this any more, sorry.
